### PR TITLE
Listing uiupdate

### PR DESCRIPTION
**Pull request by ychai23**
Created new ui for admin to view open job postings
* table view
* edit and delete
* click row to view application info

### CODE REVIEW

**Review by jinyoungbang — CHANGES_REQUESTED** [review]
src/components/Admin/AdminComponents/ListingDash.js
  Line 11:8:   'Grid' is defined but never used              no-unused-vars
  Line 17:8:   'InputLabel' is defined but never used        no-unused-vars
  Line 26:8:   'IconButton' is defined but never used        no-unused-vars
  Line 33:11:  'id' is assigned a value but never used       no-unused-vars
  Line 97:11:  'classes' is assigned a value but never used  no-unused-vars

Can you handles these minimal issues just by deleting them? It would be great to minimize warnings early in the process!

**Review by jinyoungbang — CHANGES_REQUESTED** [review]
Thanks for the fix! There seems to be a bug – when I click on the rows, I seem to get this error. Is there a fix for this? (or am I doing something wrong on my end?)

Screen Shot 2021-06-09 at 12 22 13 AM

**Comment by ychai23** [comment]
I didn't change anything from that file and the lines look different in my branch so I'm not sure. Line 26,27 isn't in the file ApplicantDashboard.

**Comment by jinyoungbang** [comment]
Try pull the most recent code from the main branch and I think the error should popup.

@ychai23 I found the issue – the problem with just linking the id of the applications is that we aren't able to pass states to our new component. When clicked on a row, the title prop should be passed to the applicantdashboard component using react-router-dom

Screen Shot 2021-06-09 at 10 43 32 AM

Ideally, we should avoid using window.location.href but using react-router for linking. 

Summary: 

- Use react router dom for linking
- Look at the example and see how the title of the jobposting is passed as a prop called "jobTitle".

Let me know if you have any other questions!

**Comment by ychai23** [comment]
@jinyoungbang should be fixed i tested it and it can direct to the new ui for viewing applicants. lemme know if it works.

**Review by jinyoungbang — APPROVED** [review]

**Pull request merged**
